apiVersion: apps/v1
kind: Deployment
metadata:
  name: talentmanager-frontend-deployment
  labels:
    app: talentmanager-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talentmanager-frontend
  template:
    metadata:
      labels:
        app: talentmanager-frontend
    spec:
      containers:
      - name: talentmanager-frontend
        image: 11700345/talentmanager-frontend:latest
#        env:
#        - name: DB_USERNAME
#          value: bewire_1
#        - name: DB_PASSWORD
#          value: PXsql2020
        ports:
          - name: http-port
            containerPort: 80
          - name: nodejs-port
            containerPort: 4200
#        volumeMounts:
#          - name: talentmanager-backend-data
#            mountPath: "/var/talentmanager-backend_home"
#          - mountPath: /var/run/docker.sock
#            name: dockersock
#            readOnly: false
#      volumes:
#        - name: talentmanager-backend-data
#          persistentVolumeClaim:
#            claimName: talentmanager-backendgluster-claim
#        - name: dockersock
#          hostPath:
#            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: talentmanager-frontend
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30005
    - name: nodejs
      port: 4200
      targetPort: 4200
      nodePort: 30420
  selector:
    app: talentmanager-frontend
  externalIPs:
    - 10.128.14.27
